import { amount, rules } from './model.js';

const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const list = values => values?.length ? `<ul class="muted">${values.map(v=>`<li>${esc(v)}</li>`).join('')}</ul>` : '';
const select = (name,label,selected,options) => `<div class="field"><label for="${name}">${label}</label><select id="${name}" name="${name}">${options.map(([value,text])=>`<option value="${value}" ${String(selected)===String(value)?'selected':''}>${text}</option>`).join('')}</select></div>`;
const actionLabel = action => `${action.type}${action.plot_id ? ` plot #${action.plot_id}` : action.plot_ids ? ` ${action.plot_ids.length} plot(s)` : ''}`;

export function guidedPage({state,plan,draft,status,busy,executionBusy}) {
  const settings=state.planSettings, insights=plan?.insights, next=insights?.next_action;
  const pending=status.pending;
  const locked=executionBusy||!!pending;
  const disabled=locked?'disabled':'';
  const selected=plan?.selected;
  const preparation = !state.portfolio.wallets.some(w=>w.plots.length);
  return `<div class="page-head"><div><div class="eyebrow">An active plan for both wallets</div><h1>Make the next move count.</h1><p class="subtitle">Refresh holdings, compare returns, then review one action with your wallet.</p></div></div>
  <section class="card"><div class="card-head"><h2>Your operating plan</h2><span class="tag">${settings.enabled?'Updates with wallet reads':'Rebuild on demand'}</span></div><form id="guided-form"><div class="fields three">
  ${select('planDays','Investment horizon',settings.days,[[30,'30 days'],[90,'90 days'],[365,'365 days']])}
  ${select('planFunding','Upgrade funding',settings.funding,[['harvest','Harvest-funded'],['extra','Extra investment allowed']])}
  ${select('planObjective','Rank by',settings.objective,[['crop','Net CROP'],['eth','Operating ETH']])}</div>
  <label class="check"><input name="planEnabled" type="checkbox" ${settings.enabled?'checked':''}> Rebuild after successful wallet refreshes</label>
  <div class="buttons" style="margin-top:16px"><button class="btn primary" type="submit" ${busy||locked?'disabled':''}>${busy?'Evaluating plan…':'Refresh & rebuild plan'}</button><button class="btn" type="button" data-tab="scenarios">Edit prices, fees & competition</button>${plan?'<button class="btn small" type="button" id="export-guided">Export active plan</button>':''}</div></form>
  <p class="muted" style="margin-top:12px">Uses saved Strategy lab assumptions, rebased to now. Monitoring runs every 30 seconds while this page or plugin is open and visible when enabled in Overview. Each wallet keeps its own CROP and ETH budget.</p></section>
  ${preparation?`<section class="card actions"><div class="card-head"><h2>Prepare the launch</h2><span class="tag">Awaiting owned plots</span></div><p>Plan ${(state.portfolio.expected_total_plots*rules.planting.cost_crop).toLocaleString()} CROP for initial planting. Keep a network-fee reserve in each wallet, then use fresh CROP quotes to decide any upgrade budget.</p><p class="muted">Mint and refresh both wallets to discover your actual traits. A Golden Acre starts with more weight, but its next upgrade must still beat the cost of other opportunities.</p><div class="buttons"><button class="btn" data-tab="overview">Review wallet funding</button><button class="btn" data-demo>Explore a fictional farm</button></div></section>`:''}
  <section class="card actions" aria-label="Next guided action"><div class="card-head"><h2>${next?.type?esc(actionLabel(next)):'Your next action'}</h2><span class="tag">${esc(next?.status?.replaceAll('_',' ')??'Plan not calculated')}</span></div><p>${esc(next?.why??'Rebuild the plan to calculate the next step from both wallets and your current assumptions.')}</p>${next?.wallet_id?`<p class="muted">Wallet: ${esc(state.portfolio.wallets.find(w=>w.id===next.wallet_id)?.label)} · ${esc(next.due_at_utc??'')}</p>`:''}${next?.crop_shortfall_wei!=null?`<p>Additional liquid CROP needed: ${amount(next.crop_shortfall_wei,2)}</p>`:''}${list(plan?.errors)}${list(insights?.required_inputs)}
  ${next?.status==='ready_for_review'?`<button class="btn primary" id="prepare-guided" ${disabled}>Prepare & simulate next action</button>`:''}</section>
  ${selected?`<section class="card actions"><div class="card-head"><h2>Returns and stress cases</h2><span class="tag">Best among evaluated strategies</span></div><p class="muted">${esc(selected.policy.replaceAll('_',' '))} · ${selected.budget_fraction}% budget ceiling · ${settings.days} days. Each stress case reruns this policy with changed assumptions.</p><div class="table-wrap"><table><thead><tr><th>Case</th><th class="number">Net CROP</th><th class="number">Operating ETH</th></tr></thead><tbody>${[...(plan.hold?[{label:'Keep current farm · no actions',...plan.hold}]:[]),{label:'No upgrades · current assumptions',...plan.baseline},{label:'Selected policy · current assumptions',...selected},...plan.stress].map(r=>`<tr><td>${esc(r.label)}${r.status!=='ok'?list(r.errors):''}</td><td class="number">${amount(r.net_crop_wei,0)}</td><td class="number">${amount(r.operating_eth_wei,6)}</td></tr>`).join('')}</tbody></table></div>${selected.funding_ready===false?'<div class="banner">Funding is conditional: an initial CROP purchase has no known quote. The ETH budget is not verified.</div>':''}${list(selected.blocked)}${selected.policy==='hold'?'<p class="muted">Hold leaves rewards pending. Its ETH figure values that inventory; a later claim can incur fees before tokens can be sold or reinvested.</p>':''}<p class="muted">Operating ETH uses your exit price and fees; it is not realized profit. Limited Granary reserves can reduce forecast weather bonuses; this model assumes the buffer can fund them. Future liquidity, prices and competing farms remain uncertain.</p><details class="detail"><summary>Upcoming strategy steps</summary><table><thead><tr><th>Day</th><th>Wallet</th><th>Step</th><th>CROP</th></tr></thead><tbody>${selected.actions.slice(0,12).map(a=>`<tr><td>${a.day}</td><td>${esc(a.wallet_id)}</td><td>${esc(actionLabel(a))}</td><td>${amount(a.crop_wei,0)}</td></tr>`).join('')}</tbody></table><p class="muted">Future steps are recalculated after each receipt. Export the active plan for the full ledger.</p></details></section>`:''}
  ${insights?.rare_first?`<section class="card actions"><h2>Where the next CROP works hardest</h2><p>${esc(insights.rare_first.explanation)}</p><p class="muted">Rarest next step: #${insights.rare_first.candidate.plot_id} → level ${insights.rare_first.candidate.to_level}. Best next-step efficiency: #${insights.rare_first.best_next_step.plot_id} → level ${insights.rare_first.best_next_step.to_level}.</p><div class="table-wrap"><table><thead><tr><th>Independent upgrade path</th><th>Rarity</th><th class="number">Cost · CROP</th><th class="number">Extra earned CROP</th><th>Burn recovered</th></tr></thead><tbody>${insights.upgrades.slice(0,12).map(r=>`<tr><td>#${r.plot_id} · ${esc(r.wallet_label)}<small>Level ${r.from_level} → ${r.to_level}</small></td><td>${rules.plots.rarities[r.rarity_tier].name}</td><td class="number">${amount(r.crop_cost_wei,0)}</td><td class="number">${amount(r.marginal_crop_wei,0)}</td><td>${r.crop_break_even_day==null?'Beyond horizon':'Day '+r.crop_break_even_day}</td></tr>`).join('')}</tbody></table></div><p class="muted">Each row assumes all owned plots are planted first and only that path changes. Do not add the rows together. Recovery excludes gas and NFT resale value.</p><h3 style="margin-top:20px">Cost of delaying dormant plots</h3><div class="stats">${insights.early_entry.map(r=>`<div class="stat"><div class="label">${r.delay_days}-day planting delay</div><div class="value">${amount(r.foregone_crop_wei,0)}</div><div class="foot">Foregone modeled CROP</div></div>`).join('')}</div><details class="detail"><summary>Diagnostic assumptions</summary>${list(insights.assumptions)}</details></section>`:''}
  <section class="card actions" aria-label="Human approval"><div class="card-head"><h2>Human approval</h2><span class="tag">${esc(executionBusy?'Checking…':status.phase.replaceAll('_',' '))}</span></div><p>Public wallet tracking works without connecting. Connect MetaMask when you are ready to review planting, one-level upgrades or claims. Select the intended account in MetaMask, then connect again when moving between your two wallets.</p><p class="wallet-address">${status.connected?esc(status.account)+' · chain '+esc(status.chain_id):'Wallet not connected'}</p><div class="buttons"><button class="btn" id="connect-wallet" ${executionBusy?'disabled':''}>Connect MetaMask</button>${status.connected&&status.chain_id!==4663?'<button class="btn" id="switch-wallet">Switch to Robinhood Chain</button>':''}</div>
  ${!preparation&&!state.portfolio.is_demo?`<details class="detail"><summary>Review a specific action</summary><p class="muted">Manual review does not imply that the action is profitable. It still requires public contract checks and wallet approval.</p><form id="manual-action-form"><div class="fields two">${select('manualType','Action','claim_all',[['claim_all','Claim all pending plots in this wallet'],['claim','Claim this plot'],['plant','Plant one plot'],['upgrade','Upgrade one level']])}<div class="field"><label for="manualPlot">Wallet and plot</label><select id="manualPlot" name="manualPlot">${state.portfolio.wallets.flatMap(w=>w.plots.map(p=>`<option value="${p.token_id}">${esc(w.label)} · #${p.token_id} · level ${p.level??'?'}</option>`)).join('')}</select></div></div><button class="btn" type="submit" ${disabled}>Prepare manual action</button></form></details>`:''}
  ${draft?`<article class="transaction-review"><div class="card-head"><h3>${draft.type==='approve'?'Approve exact CROP allowance':esc(actionLabel({type:draft.type,plot_ids:draft.plot_ids}))}</h3><span class="tag">Simulation passed</span></div><dl><div><dt>From</dt><dd class="wallet-address">${esc(draft.from)}</dd></div><div><dt>Contract</dt><dd class="wallet-address">${esc(draft.to)}</dd></div><div><dt>CROP spent by this transaction</dt><dd>${amount(draft.crop_cost_wei,2)}</dd></div>${draft.type==='approve'?`<div><dt>Allowance for ${esc(draft.requested_type)}</dt><dd>${amount(draft.approval_amount_wei,2)} CROP</dd></div>`:''}<div><dt>Execution gas estimate</dt><dd>${amount(draft.network_cost_estimate_wei,10)} ETH</dd></div><div><dt>Execution gas ceiling</dt><dd>${amount(draft.network_cost_limit_wei,10)} ETH</dd></div><div><dt>Checked block / review expires</dt><dd>${draft.block_number} / ${esc(new Date(draft.expires_at).toISOString())}</dd></div></dl>${list(draft.notes)}<p class="muted">MetaMask shows the final transaction and network fees. An allowance approval is a separate transaction; the intended planting or upgrade needs another review after confirmation.</p><details><summary>Transaction data</summary><pre>${esc(draft.data)}</pre></details><div class="buttons" style="margin-top:16px"><button class="btn primary" id="submit-action" ${disabled}>Request MetaMask approval</button><button class="btn" id="discard-draft" ${disabled}>Discard review</button></div></article>`:''}
  ${pending?`<article class="transaction-review"><h3>Outstanding ${esc(pending.type)} · ${esc(pending.phase.replaceAll('_',' '))}</h3><p class="muted">Finish checking this transaction before preparing another. A missing hash may mean the wallet broadcast it; the lock is saved across reloads.</p>${pending.hash?`<a href="https://robinhoodchain.blockscout.com/tx/${esc(pending.hash)}" target="_blank" rel="noopener noreferrer" class="wallet-address">${esc(pending.hash)}</a>`:''}<form id="pending-form">${!pending.hash?'<div class="field"><label for="pendingHash">Transaction hash from MetaMask activity</label><input id="pendingHash" name="pendingHash" autocomplete="off"></div>':''}<button class="btn" type="submit" ${executionBusy?'disabled':''}>Check transaction</button></form><details class="detail"><summary>MetaMask speed-up or cancellation</summary><p class="muted">Copy the replacement transaction hash from MetaMask. The companion clears the lock only after a canonical receipt proves that this wallet's same nonce was consumed. A cancellation does not complete the planned game action.</p><form id="replacement-form"><div class="field"><label for="replacementHash">Replacement transaction hash</label><input id="replacementHash" name="replacementHash" autocomplete="off"></div><button class="btn" type="submit" ${executionBusy?'disabled':''}>Check replacement</button></form></details></article>`:''}
  <p class="muted" style="margin-top:14px">Transactions stay locked while awaiting a receipt. No seed phrase, private key or spending permission is stored. Minting, swaps and wallet transfers remain manual on the game or your chosen exchange.</p></section>
  <section class="card actions"><h2>Local action journal</h2>${state.executionLog.length?`<div class="table-wrap"><table><thead><tr><th>Time</th><th>Wallet / action</th><th>Status</th><th>Receipt</th></tr></thead><tbody>${[...state.executionLog].reverse().map(r=>`<tr><td>${esc(r.at)}</td><td>${esc(r.wallet_id)} · ${esc(r.type)}</td><td>${esc(r.status)}</td><td>${r.hash?`<a href="https://robinhoodchain.blockscout.com/tx/${esc(r.hash)}" target="_blank" rel="noopener noreferrer">View transaction</a>`:'—'}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">No companion transactions recorded. Export the workspace to back up this journal.</p>'}</section>`;
}
